language: scala
os: linux
jdk:
- openjdk14
- openjdk11
- openjdk8
scala:
- 2.12.11
- 2.13.2
env:
  global:
  - secure: fIwS3wctOKMs+yEE8s4lvtcwJEgktzHCliK+D7ShJ8Lia98JWCc/JhGMlCtX3RFkQjIy0syIJKw2eQglxNqqFqoO7EsQhipgf9An+hVVbw/Tn7t1xIslSw9EzFUTRA/wP00JLKunUizR6YxuLmq9VbxzJdK+kr5v1g3ggq311sKE8bpWWqTvixKkhQg2ULyqHZ3cPcMnxAmLG8jiddgnN7PcDL0MOePiSQeNawwFNoI7rp6rZRfREHyrHrwIo7USfPP8R8Mk0z9b08MxW0ZG4P04M0jWZRobqXMYz/PW2GALn0UQPDjg+8OI4qtmmunPYR0mwkgRumpem8LhIjHoOXZu/Oq8OqU+76x/gcEU25nkz3EH59si/kGOxObJUFUil6pt4QjA/QSI7dzC+yQIabOfJEOH8D3q9Eb6JBRWIf26pj02b2IbWmPFEooxQXL7XNQ/eYmnrw0UhOQvBPJ+YntQmpHlJKNwPD5lIOrqvLWoUWYe5oB83o2G2CyybzuPBrioUxr4XcGFiq4W5X3rjCQpNHTPS1QOPLukisYMdXQPkcTsvcrEUHvA2bH6a2gmvG7ykR9iHqPrpARqxt1qO84RbgK/pJhNcayZKRDrNjxHxiaQJXT5xlIjld1uxAM7kRUunuWNm57gi170LveMFK668PVcUAQTrD09eosrbKQ=
  - secure: MlwQtz4tO1mmNmPE2PIxYI552puyQpQa690C6ZOldvL0zGhw5mgj5JD8G4I4RmuaNev7mpdnBecoTEg6q2pxPTHQEgQmHVX5X7SPf1Loyes35AWzscGhWVwFdOF6ZqccB8PUZrUZ2CAD83JjG39/PGk5bxqwBNFkeFBQrGYhDuL5caqJ9/MTfKHM/NoR66ygigscnsfb8qwtS1wpSJ5LbFrC2KFzGfDXuP5bjkz9PZdQrS8c7nC63KcdeENpqwdrWWzrw3hf0uSh3xEZp7SziDZ0wMOX6lmIIzRjmlJIPF4BD9MsDiPqhmwJk4MdvKtWAzKJTnGxmygNLVw7YKnqULnWjsOmNfraHGEkqSE/DCccsjAIzYP0vD7V+JgXOk5JLvwLGff3VW9457f2pAMWJgliL9r136DKLMvxiMpXgFp3BkZHsc80Ve1G9nqgGMqp1zrCgE78mqQJ5AFQczfTZOXNsjLkGYgs38k7aLiCAm8p9ZHYBo4DZiaPKc/K2XkBmTP+2KuHpwXGUbnvfFFoHuwV1iDh+CeEo1N4UZrhwPCXTNaJKYQCQ8d7u2Vvt27Ido+IfvSnKvBlHMkpmzAdyF5dhT3jR0xEartpMw8MmUnKVxanJitfLME1qInf7INhFkkRECj9yFpFA1kCM+dszxdEEaBmD0D004xd0rU4Y3c=
  - secure: tkDiJZF3UfKYJv/FZM7JlkhHmdf9DvDMHzc/dQbsqB80y4cj+DPwv6XETYrBtnjx7WsVo6bA4uE92NZqYSRjTZDjWjF2k+ViTFNVSVLm+h7ujIs8Xo41tWRIV/73bkog5+VNwHX1KHG9ih6EHkcpM+Qllvl11i+3h04WX9ymWE4gZAwI504l1cVE0O8q0j13p4UyHxq7egT4JQYu2yS3PX/a3S5KUVSHk/UEOlQt+P8gqLmvHWIn4yApRluFY1d7aFRlAL4pKHgAJCCytT91XqyshCKd8jEQMvW+D6RYs+TFQNM5gAaMFBfADnnnbanVLYAAZNEVRD65FdnqremESJo9z+sw9oZDGNI1STP8k1Q4+rBPZUyAWR3fRX8XmFrks5EcyNDScUY/Ujl4u0xVi90+KwCC+Ywp17IQLP23JjN3bx0r+ZUICkpKuymWY1mjDj2iZsxJEZUY9aPHXBOEI3i7/f7pTcfdgn+C0tUTBCcvTQu754cBKzNFLDo1DIdTnxtyyfqUco8E2s7o1sOVBzdm0olyoqh50R2aSj+uHIbwaj15GH01CjwxhwIeVqK92Map+U8ExX3yE+V9U0EFJfVD39s7qVjiVBsseb48LPaNSINN+bPenKSNzPACwVTlM/Rq3NNqrto76IgwRigEcdN4xmfR0Agcjsx24FZs1So=
  - secure: DTlD2JnbDeOfyeICJUdGwICpi8Hx6PHj+fe0csqL0x+rCA2lDhHmC6YFU/eS/6i9xGV53WYX4a6EDCFI5BiUmeUIWZL5H+SfQcyRKNIGzK0tHkKBo2iXfTeg6W8oJbYk2FbMKQztpmJBuKS2+KrSj0gPH/YDJW9tXpj5RYaFgGn6+pnoSCdTzzhQJIAagbpevKYFL0B/nJPkY7bzrHdjdzj+KE52ERNmBOyq9Bv0C6wZRGvxouITViz2vvlPX0w9metXI/mBFstNZrBqu62VUAjisNFWn61MU+8gQ9dd4FbgNmUF+NEGMe3+bcj2EJcPmbV5am9MN6NMZOx/aL3L8g1BbCiToVSj5baCHQwjceipmr2hpyZQQT9+70I6o5o8dnTLq1b+Ytc58V5cpj7hClSYJhvF90AgCRKe/ZoIqRLukrq1J9tUu+f9w8JLi85muuOEOu/yVC2qdfppW+hFPuP4Pn+zhUaRRd7jXITYr4b65fpDVwnvXkYMbl64mme5dQxEfxe6cIuaEB4Osdsp8iTNdKchcD+k6EJOaB3yZ9XFQ9xPkC3VEMIjDMHdZI+BTDC0KlMBiLjCNL+RxNTZd7fDk8Td8y6229yzxSw/OKFaYzKEOqtxdha5ciHwqasE2C8RSs34MJ8Sj4ZVNqfbphlu/6+LKYxd/xFeOYaQ6g8=
script:
- |
  if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" && "$TRAVIS_SCALA_VERSION" == "2.12.11" ]]; then
    sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  else
    sbt ++$TRAVIS_SCALA_VERSION clean test
  fi
after_success:
- |
  if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" && "$TRAVIS_SCALA_VERSION" == "2.12.11" ]]; then
    bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  fi
before_cache:
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/918d848d331e204d005f
    on_success: change
    on_failure: always
    on_start: never
after_script:
  - bash ./telegram_notification.sh

