name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: sbt +test
    - name: Notify via telegram
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TELEGRAMBOTTOKEN }}
        chatId: ${{ secrets.TELEGRAMCHATID }}
        jobStatus: ${{ job.status }}
        skipSuccess: 'false'